//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commentar
    {
        public int Commentar_id { get; set; }
        public string Commentar_title { get; set; }
        public string ExerciceNr { get; set; }
        public string Commentar1 { get; set; }
    }
}
