//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteWeb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User_Projet
    {
        public int user_id { get; set; }
        [Required(ErrorMessage ="Obligatoire")]
        public string name { get; set; }
        [Required(ErrorMessage = "Obligatoire")]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }
        [Required(ErrorMessage = "Obligatoire")]
        [DataType(DataType.Password)]
        public string password { get; set; }
        [Required(ErrorMessage = "Obligatoire")]
        public string Niveau { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
